version: '3'
services:
  mysql:
    networks:
      - deepnetwork
    image: mysql:${MYSQL_VERSION}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    container_name: mysql
    restart: on-failure
    volumes:
      - "${DATA_DIR}/mysql:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: deepanshu

  nextcloud:
    networks:
      - deepnetwork
    image: nextcloud:${NEXTCLOUD_VERSION}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    container_name: nextcloud
    restart: on-failure
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html"
      - "${DATA_DIR}/mysql:/var/lib/mysql"
    ports:
      - 8080:80
    links:
      - mysql:mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: deepanshu
    depends_on:
      - mysql

  reverse-proxy:
    networks:
      - deepnetwork
    image: nginx
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    container_name: nginx-proxy
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - nextcloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  deepnetwork:
    driver: bridge 
